#include <types.h>
#include <deployment.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void user_do_ping_spg 
    (software__simple_type* data_source);
void software__do_ping_spg 
    (software__simple_type* data_source)
{

  user_do_ping_spg (data_source);
}

void __po_hi_driver_sockets_send 
    (__po_hi_device_id dev_id);
void ocarina_drivers_ip_pohic__spg_eth_linux_sender_i 
    (__po_hi_device_id dev_id)
{

  __po_hi_driver_sockets_send (dev_id);
}


